### ISSUE TITLE
What's the status of this project?

### ISSUE THREAD

**Issue by afidegnum** [cuducos/webassets-elm#7]
HI, 

I would like to ask if this project can be used in production? 

I am trying to generate sample ELM template from Python/Flash which will be compiled at the end and would like to use webassets-elm.

Can you give some guidance about it ?

**Comment by cuducos** [comment]
Hi, this project has code that works as far as I know. I see no problem in deploying it to production.

Regarding using it with Flask, can you be more specific? I mean, there’s an example of usage with Flask in the `README.rst` – from there what are you issues, doubts, limitations?

**Comment by afidegnum** [comment]
well, let's take for example a CRUD page with listing, using models, i want to automatically insert the fields and its data types in elm with sample templates once all automatically generated in ELM, they will be compiled to a js file instead of manually writing all type aliases and models before generating the js file. 

I don't know if i m clear.

**Comment by cuducos** [comment]
I'm sorry @afidegnum, I'm afraid you misunderstood what the [webassets](https://github.com/miracle2k/webassets/) package is about and, consequentially, overrated the expectations for this filter (this project is merely a webassets filter, as stated in the `README.md`: _Filter for compiling Elm files using webassets_).

[This is the official definition of the webassets package](https://webassets.readthedocs.io/en/latest/):

> webassets is a general, dependency-independent library for managing the assets of your web application. It can merge and compress your CSS and JavaScript files, supporting a wide variety of different filters, and supports working with compilers like CoffeeScript or Sass.

An that is the purpose of this filter: to allow you to compile Elm files using webassets pipeline.

Unfortunately, what you are asking is totally out of this scope and not in the plans for such a filter.
